Update deploy.yaml

diff --git a/deploy.yaml b/deploy.yaml
--- a/deploy.yaml
+++ b/deploy.yaml
@@ -46,12 +46,16 @@ Resources:
           Value: "HINNA"
       UserData: 
         Fn::Base64: 
-          Fn::Join:
-            - ""
-            - - "#!/bin/bash \n"
-              - "sudo /opt/bitnami/wp-cli/bin/wp user create admin "
-              - !Sub "${CustomerEmail} --user_pass=${CustomerPass} --role=administrator || echo 'Error creating user' >> /tmp/wp_user_creation.log"
-              - "echo 'Admin user created successfully' >> /tmp/wp_user_creation.log"
+          !Sub |
+            echo "Waiting for WordPress to initialize..."
+            until sudo /opt/bitnami/wp-cli/bin/wp --info > /dev/null 2>&1; do
+              sleep 5
+            done
+            echo "WordPress initialized."
+      
+            # Create the admin user with correct email and password
+            sudo /opt/bitnami/wp-cli/bin/wp user create admin "${CustomerEmail}" --user_pass="${CustomerPass}" --role=administrator || echo 'Error creating user' >> /tmp/wp_user_creation.log
+            echo 'Admin user created successfully' >> /tmp/wp_user_creation.log
 
   StaticIp:
     Type: AWS::Lightsail::StaticIp
